name: Deploy Flask App

on:
  push:
    branches:
      - main

env:
  HEALTHCHECK_URL: http://

jobs:
  Build-test-Deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Virtual venv
        run: |
          sudo apt install python3.12 -venv -y
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unitttests
        run: |
          python3 -m unittest test_app.py

      - name: Deploy Flask App
        run: |
          nohup python3 app.py &

  
    
